### ISSUE TITLE
Secure Context

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/wry#10]
Having the webview content be considered "secure" is something that users may want to enable if they want to use geolocation, camera, high-resolution timers etc. Can we have a config that allows them to turn this on for all platforms?

### Background: 
A secure context is determined by browsers using file://, localhost, https:// - since code injection is none of these, we don't have a secure context...

**Comment by nklayman** [comment]
At least on Linux, a custom protocol can be a secure context. If that is true for other platforms as well, #15 would fix this too.

**Comment by wusyong** [comment]
As custom protocol being added, does this mean this issue is also resolved?

**Comment by lucasfernog** [comment]
Can someone confirm that `window.isSecureContext` is true on all platforms? Noah checked on Linux.

**Comment by lucasfernog** [comment]
I can do it later today.

**Comment by wusyong** [comment]
It's true on windows but nay on mac. :(

**Comment by wusyong** [comment]
Just tested `window.crypto` on mac and it's working despite `window.isSecureContext` is false.
I think we can close this since the main concern is tracking which features are blocked by this.
And it seems safari/wkwebview [don't like](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts) the idea of secure context so it won't affect us.

**Comment by nothingismagick** [comment]
can you verify that getUserMedia works?

**Comment by wusyong** [comment]
It seems safari doesn't require [secure context](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaDevices).

But wkwebivew doesn't have [this](https://bugs.webkit.org/show_bug.cgi?id=188360) unfortunately :(

**Comment by nklayman** [comment]
This can be closed then, right?
