### ISSUE TITLE
Transparency not working on Windows 11

### ISSUE THREAD

**Issue by UmGarcia** [tauri-apps/wry#1026]
Using title bar example code and others codes the transparency don't work on windows 11 using version 0.33.0

![image](https://github.com/tauri-apps/wry/assets/8272623/1fed5b98-ba3c-4b22-9f1c-23369e8326a2)

When I maximize and minimize the window it becomes transparent, but with borders:

![image](https://github.com/tauri-apps/wry/assets/8272623/d7cf10d1-b56e-4956-a7ee-24c26487a74b)

When using version 0.24.4 the screen respects transparency:

![image](https://github.com/tauri-apps/wry/assets/8272623/134864e2-4a0d-4e2d-93a1-a0098c4df685)

I'm new using WRY and Rust, so I have no idea what the problem could be, but I validated that all versions above 0.24.4 are not complying with transparency in Windows 11.

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [ ] No

**Comment by amrbashir** [comment]
this is because the shadows are turned on when the window is created, so you need to call https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/application/window/struct.WindowBuilder.html#method.with_undecorated_shadow to disable it while creating the window then enable it back (if you want) using https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/application/window/struct.Window.html#method.set_undecorated_shadow

See this example https://github.com/tauri-apps/window-vibrancy/blob/ce6e299a3bc98bd1d0f322c3b922fe8634f09e8e/examples/winit.rs#L21-L36

**Comment by UmGarcia** [comment]
> this is because the shadows are turned on when the window is created, so you need to call https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/application/window/struct.WindowBuilder.html#method.with_undecorated_shadow to disable it while creating the window then enable it back (if you want) using https://docs.rs/wry/latest/x86_64-pc-windows-msvc/wry/application/window/struct.Window.html#method.set_undecorated_shadow
> 
> See this example https://github.com/tauri-apps/window-vibrancy/blob/ce6e299a3bc98bd1d0f322c3b922fe8634f09e8e/examples/winit.rs#L21-L36

I'm extremely grateful for that clarification, I didn't imagine that shadowing enabled or not in version 0.24.4 doesn't occur.

I just tested it and now it is as expected.

Thank you!
