### ISSUE TITLE
Is there any way to share buffer between front and backend?

### ISSUE THREAD

**Issue by yollpoll** [tauri-apps/wry#1035]
I use tauri,In my case,I pass lots of binary data from backend to front (about 200mb,need 2-3s),Front use this binary to draw chart on canvas ,is there any way to share buff between front and backend?

**Comment by FabianLars** [comment]
Not yet, no. The webviews don't have apis for that yet. Well, Windows does but only on win10+ (we still support 7 & 8) and iirc there were problems with the apis 🤔 
And we hoped we could use the new SharedArrayBuffer (https://github.com/tauri-apps/tauri/discussions/6269) in webkit (macos and linux) at some point but **i** don't see how, but i'm more of a windows guy so i may be missing something especially since there are like no docs for wkwebview and webkitgtk...

Did you try [custom protocols](https://docs.rs/tauri/latest/tauri/struct.Builder.html#method.register_uri_scheme_protocol) or even v2 already? It handles binary data much better, especially in v2 where it it's a bit more async-ish to block the main thread less.

Either way, shared memory buffers is something we're interested in for sure and we'll keep looking for a solution but it's not something you will get your hands on anytime soon :/
