### ISSUE TITLE
getDisplayMedia() does not work on MacOS Sonoma 14.0+

### ISSUE THREAD

**Issue by tarushnagpal** [tauri-apps/wry#1101]
**Describe the bug**
If you try getting the user's screen capture it fails with a `NotAllowedError`, this is also an issue reported in tauri, https://github.com/tauri-apps/tauri/issues/2600

**Steps To Reproduce**
- Change the simple.rs example to display any webpage that has a getDisplayMedia call (Gmeet, etc)
- Run `cargo run --example simple`
- Try to share screen from the video calling app
- It will fail

**Expected behavior**
Ideally, the display media should be captured and shown on the screen, just like camera and audio work out of the box

**Screenshots**
Copied the screen shot from the same issue
![image](https://github.com/tauri-apps/wry/assets/24592076/b0c4cd76-55ef-40a8-9b59-e418ae91ac86)

**Platform and Versions (please complete the following information):**
OS: macOS 14.0 (23A344)
Rustc: 1.72.1

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [x] No

**Comment by pewsheen** [comment]
It looks like the fix https://github.com/tauri-apps/wry/pull/694 suppressed the permission prompt and just denied the permission request. After I commented out the patch, the prompt showed up and worked as expected.

Since I have messed up my environment, the prompt no longer shows up and always grants permission, I can't test if the original issue (https://github.com/tauri-apps/tauri/issues/4750) still persisted after macOS 14. If it doesn't, maybe we can do a version check and decide if the patch should be used.

Ps. A mini repo to test the capture function after commenting out the fix: https://github.com/pewsheen/screen-capture-test

cc @FabianLars @lucasfernog

**Comment by tarushnagpal** [comment]
@pewsheen Hey, I've raised the PR, tested locally on my MacOS 14.0 and it works fine, let me know if anything else is required

**Comment by FabianLars** [comment]
@tarushnagpal Did you test whether this messes with the microphone/camera permissions on 14.0?

**Comment by tarushnagpal** [comment]
Yes @FabianLars I checked with "audio" only, "video" only and "audio and video", only seeing a single permission request for microphone/camera on 14.0

**Comment by stolinski** [comment]
Sorry for the duplicate comment, but I figured I should post here too. I'm once again not seeing the screen share permissions prompt in beta.10, tauri-runtime-wry v2.0.0-beta.8

Is anyone else seeing this? Getting the same error I was seeing before

Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

Seems like https://github.com/tauri-apps/tauri/issues/8979
https://github.com/tauri-apps/wry/pull/1186
when the duplicate perm prompts are fixed, screen recording breaks. Is that accurate / is anyone else seeing this?

Also I tried to give https://github.com/pewsheen/screen-capture-test a look to confirm, but the repo doesn't seem to exist anymore.

**Comment by pewsheen** [comment]
> Sorry for the duplicate comment, but I figured I should post here too. I'm once again not seeing the screen share permissions prompt in beta.10, tauri-runtime-wry v2.0.0-beta.8
> 
> Is anyone else seeing this? Getting the same error I was seeing before
> 
> Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
> 
> Seems like [tauri-apps/tauri#8979](https://github.com/tauri-apps/tauri/issues/8979) #1186 when the duplicate perm prompts are fixed, screen recording breaks. Is that accurate / is anyone else seeing this?
> 
> Also I tried to give https://github.com/pewsheen/screen-capture-test a look to confirm, but the repo doesn't seem to exist anymore.

Hmm.. #1186 has not been released yet. It shouldn't be applied to your app.
