### ISSUE TITLE
Ability to set custom User Agent

### ISSUE THREAD

**Issue by aditsachde** [tauri-apps/wry#276]
**Is your feature request related to a problem? Please describe.**
It'd be useful to set a custom UA for identifying desktop apps. Additionally, some sites require UA spoofing to work.

**Describe the solution you'd like**
Add a way to allow setting a custom UA for a webview.

**Describe alternatives you've considered**
N/A

**Would you assign yourself to implement this feature?**
- [x] Yes
- [ ] No

**Additional context**
N/A

I'd like to make an attempt at adding this feature, the main question I have is whether it's reasonable to implement it as a property on `WebViewBuilder` and `InnerWebView::new`, or if there is a better place.

**Comment by shirakaba** [comment]
Exposing it on WebViewBuilder may make sense for convenience, but ideally it should be possible to update UA on the WebView at any moment post-construction, because it is essentially a dynamic property rather than something you might only want to set once.

For example, you might have an app that augments a user's YouTube and Netflix experiences, and therefore might have to set a different UA on each site to unlock different features (e.g. text subtitles rather than vector subtitles on Netflix). Ideally the API needs to be flexible enough to allow a user to update the UA just before navigation.

_Side-note:_ I'm not sure what the design philosophy behind WebViewBuilder is. For iOS/macOS WKWebView, for example, the only things that need to be set up at construction time are the `frame` and the [WKWebViewConfiguration](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration), and the latter can't be updated later (there is no setter). So the fact that WebViewBuilder lets you set things like URL suggests that it also offers offers APIs just out of convenience, rather than strictly construction-time necessity.
