### ISSUE TITLE
Edge try to resolve custom protocol as domain name since v0.12.1

### ISSUE THREAD

**Issue by KarlitosVII** [tauri-apps/wry#376]
**Describe the bug**
Hello,
since v0.12.1 the shorter protocol name on windows removed the underscore, so if `https://{protocol}.{url}` is a valid domain name (e.g. https://wry.exemple/ for wry://exemple/) Edge will try to resolve the domain name (and fail). This can delay the request by few seconds in worth cases.

**Platform and Versions (please complete the following information):**
OS: Windows
Rustc: 1.54

**Would you assign yourself to resolve this bug?**
- [x] Yes
- [ ] No

**Comment by wusyong** [comment]
Do you have a test case for me to compare?
custom_protocl loads really fast so perhaps I didn't notice.

**Comment by KarlitosVII** [comment]
Sure.

```rust
use wry::{
    application::{
        event::{Event, WindowEvent},
        event_loop::{ControlFlow, EventLoop},
        window::WindowBuilder,
    },
    webview::WebViewBuilder,
};

fn main() -> wry::Result<()> {
    let event_loop = EventLoop::new();
    let window = WindowBuilder::new().build(&event_loop)?;

    let webview = WebViewBuilder::new(window)?
        .with_custom_protocol(String::from("wry"), protocol)
        .with_url("wry://")? // Take 2s to load
        // .with_url("wry://_")? // <- Instant
        .build()?;

    event_loop.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::WindowEvent { event, .. } => match event {
                WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
                WindowEvent::Resized(_) => {
                    let _ = webview.resize();
                }
                _ => (),
            },
            _ => (),
        }
    });
}

fn protocol(_path: &str) -> wry::Result<(Vec<u8>, String)> {
    let content = br#"
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Test</title>
    </head>
    <body>
        Hello World
    </body>
    </html>
    "#;
    Ok((content.to_vec(), String::from("text/html")))
}
```

**Comment by wusyong** [comment]
@KarlitosVII I think this is because we try to reduce the URL length in actual URL.
Before it's `https://custom.protocol.{protocol}_{url}`, so if you didn't have any URL, it can still pass it the filter on first try.
But now it's `https://{protocol}.{url}`, you need to provide a URL host/path or the filter might take several rounds to pass it.
We also need this to make whole URL to qualify FQDN, so users won't get strange behavior when they connect to outside servers.

In reality, custom protocol closure expects a path for it to do something.
So maybe you could pass `.with_url("wry://index.html")?`.
If you just want to load a HTML file, we now have a `with_html` method which could be a lot faster.

**Comment by KarlitosVII** [comment]
If I set `.with_url("wry://index.html")?` all rel and href will be redirected to `https://wry.index.html/{url}` because I think Edge consider `wry.index.html` as the base domain of the site. So I have to trim `wry://index.html` for each requests.

```rust
fn protocol(path: &str) -> wry::Result<(Vec<u8>, String)> {
    let (content, mime) = if path == "wry://index.html/index.css" {
        (
            r#"body {
                background-color: pink;
            }"#,
            String::from("text/css"),
        )
    } else {
        (
            r#"
                <!DOCTYPE html>
                <html lang="en">
                <head>
                    <meta charset="utf-8" />
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    <title>Test</title>
                    <link rel="stylesheet" href="/index.css">
                </head>
                <body>
                    Hello World
                </body>
                </html>
            "#,
            String::from("text/html"),
        )
    };
    Ok((content.as_bytes().to_vec(), mime))
}
```

**Comment by wusyong** [comment]
oh yeah you are right. Perhaps `localhost` then. This is what we do it on tauri (so it's `https://tauri.localhost`)
I suppose trimming is valid since if you want to get the path, you should already have a call for trim.
There are also other ways to determine the folder of assets, for example we have config for it in tauri.

**Comment by KarlitosVII** [comment]
Adding a "custom domain" to the custom protocol like `wry://localhost` works well. Thank you !

**Comment by wusyong** [comment]
I'll close this if it's resolved. Welcome to open any other issue if you encounter new bugs.
