### ISSUE TITLE
Custom protocol / rpc handlers should allow async rust code

### ISSUE THREAD

**Issue by jkelleyrtp** [tauri-apps/wry#420]
Right now, RPC handlers and custom protocol take callbacks. However, in these handlers, you might want to perform some sort of async action on the Rust side. The JS is already awaiting the RPC call, so it should be possible to perform async on the Rust side, but it is not without blocking the handler's thread.

The handler and callbacks should allow some sort of async code, or allow the RPC requests to be resumed at a later point in time. It would be okay if the handlers kept async code if the response could be deferred internally, and a handle could be generated that allowed responding outside of the handler itself.

**Comment by wusyong** [comment]
Running async code will require an executor and wry should be agnostic to it IMHO.
That said, tauri does use tokio for async usage. I suppose it would be a nice enhancement for it.
The easiest way is to spawn a block_on task.

I'm actually thinking about refactoring entire RFC handling because of the performance.
WebView2 only accepts strings and JSON as arguments and this hurts the latency a lot.
Although we can use custom protocols to return blobs or bytes, the headers of request are bugged and become empty atm on WebkitGTK.
I'm proposing a minimum reproducible example toward their bugzilla. And in the meantime, let's try our best to reduce overheads as much as possible.

**Comment by lucasfernog** [comment]
On Tauri you can use the `async_runtime` module.

**Comment by jkelleyrtp** [comment]
> The easiest way is to spawn a block_on task.

Won't this block the renderer thread? This is what I'm doing currently, but it seems wrong to block the renderer to wait for a long-running task to complete.

> I'm actually thinking about refactoring entire RFC handling because of the performance.

I might just turn to sockets for communication into the runtime - it's honestly more efficient in some ways. Is there a way we could hijack the websocket protocol in the WebView for communication?

Perhaps the handler API could be refactored to support a message-based interface?


Also - as a side note - is there a good way of hijacking a canvas or webgl surface from the main thread and rendering a wgpu context into it? I feel like there should be an api for this but I haven't seen anyone else do it and it doesn't seem possible with the RPC or custom protocol code.

**Comment by wusyong** [comment]
> Won't this block the renderer thread? This is what I'm doing currently, but it seems wrong to block the renderer to wait for a long-running task to complete.

Yeah that will block it. Perhaps instead of spawning threads, you could spawn async task from `async_runtime` module as @lucasfernog suggested.

> I might just turn to sockets for communication into the runtime - it's honestly more efficient in some ways. Is there a way we could hijack the websocket protocol in the WebView for communication?

Custom protocol can't hijack existing protocol, but defining another one is possible. That's why I'm thinking it might be better to use it for WebView communication. However as I mentioned, it's kind of bugged on Linux. If you are using Linux, you might want to send the URL with some GET method approach (something like <protocol>://<path>?key=value).

> Is there a good way of hijacking a canvas or webgl surface from the main thread and rendering a wgpu context into it?

We haven't explored that yet :disappointed: 
Edit: Looks like wasm can benefit from WebGL and wgpu. Rust also has some crates for it like wgpu-rs. But it doesn't look like a simple job to integrate them

**Comment by traverseda** [comment]
Would this be something that you could use to implement streaming responses  with? That seems like a pretty big missing piece of tauri/wry at the moment. As I understand it, that would enable custom protocol to

 * implement very large file downloads and large file generation without blocking the main UI
 * Implement server-sent-event, http long polling, and other mechanisms to push to the frontend
 
Is there any way to do that without a feature like this? Being able to stream/chunk responses is of course the other half of the equation.

**Comment by amrbashir** [comment]
Closign as this have been implemented in #1017
