### ISSUE TITLE
Why was bidirectional RPC replaced by unidirectional IPC in the latest version?

### ISSUE THREAD

**Issue by nullchinchilla** [tauri-apps/wry#570]
As the title. Why was this changed made? RPC was much easier to use for passing data back to JavaScript; now I need to use hacks with `evaluate_script` calls that call some global callback in the JavaScript side, which is extremely hacky and annoying.

**Comment by wusyong** [comment]
I think this is related to https://github.com/tauri-apps/wry/issues/474
I'll close this to redirect the discussion to there.

**Comment by FabianLars** [comment]
On a side note, the bidirectional rpc was removed as part of the audit changes, so you can check the audit report in the repo to see the reasons behind it.

**Comment by FrankenApps** [comment]
I read the description of this in the report. I do understand why this could be a threat however I think this feature was very convenient, and under certain circumstances it should not be a security issue at all, so maybe developers could get the option to manually enable this?

For example all apps I have built so far using `wry`, I set up a React + Webpack application and then only bundled and loaded the build result into the binary (so there was no external JS loaded during runtime). Additionally since the console is disabled in release builds, I do not see why this should be of any concern in that case. Here is a [starter template](https://github.com/FrankenApps/wry_react_webpack_template) to illustrate the architecture.

Just to be clear: I do agree it can be problematic, but I still think that developers should be able to use bidirectional rpc when their application architecture ensures it is safe.

**Comment by amrbashir** [comment]
IIRC, along the audit recommendations, we  wanted to simplify the IPC methods and remove some overhead also the old RPC system relied under the hood on using serialization and `evaluate_script()` which had poor performance. Anyhow, we decided to let users build their bi-directional IPC system as they see fit.

Recreating the old RPC system shouldn't be that hard anyways, you could look at our old implementation  for reference.

**Comment by amrbashir** [comment]
IIRC, along the audit recommendations, we  wanted to simplify the IPC methods and remove some overhead. Also the old RPC system relied under the hood on using serialization and `evaluate_script()` which had poor performance. Anyhow, we decided to let users build their bi-directional IPC system as they see fit.

Recreating the old RPC system shouldn't be that hard anyways, you could look at our old implementation  for reference.
