### ISSUE TITLE
Unable to receive certain WindowEvent types in wry main() event_loop

### ISSUE THREAD

**Issue by jerrywrice** [tauri-apps/wry#902]
**Bug Description**
Wry application doesn't receive WindowEvent::KeyboardInput keyboard events on Windows 10 from text input field of form. 

*Steps To Reproduce:
Attached is a slightly modified version of the 'form.rs' example (zipped), which has additional match arms in its event_loop.run() handler.

**Expected behavior**
I expected to receive KeyboardInput events for each character entered to text field.

**Screenshots**
n/a
**Platform and Versions (please complete the following information):**
[form.zip](https://github.com/tauri-apps/wry/files/10962196/form.zip)

OS: Windows 10 Pro 10.0.19045 build 19045
Rustc: rustc 1.68.0 (2c8cc3432 2023-03-06)

**Would you want to assign yourself to resolve this bug?**
- [ ] Yes
- [x ] No  - not at this time, as I'm a rust newbie.

**Comment by amrbashir** [comment]
As far as I know, That's by design in WebView2. The webview2 control is separate from the win32 window and has a different focus state from the parent window and in most cases, it intercepts all events before it can reach the parent window. This issue is probably related https://github.com/MicrosoftEdge/WebView2Feedback/issues/468#issuecomment-1016993455

I am not sure what is your use-case exactly but I'd suggest looking into forwarding the needed info from JS to your rust using `window.ipc.postMessage`

**Comment by mmgeorge** [comment]
I looks like an experimental feature CoreWebView2ControllerOptions.AllowHostInputProcessing was added. Would that help with this? https://github.com/MicrosoftEdge/WebView2Feedback/issues/468#issuecomment-2289907937
